<?php

namespace ContainerZp4iImM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2PGmgL2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2PGmgL2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2PGmgL2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AjoutDishController::onAddintionDishSuccess' => ['privates', '.service_locator.sk74CaS', 'get_ServiceLocator_Sk74CaSService', true],
            'App\\Controller\\AjoutDishController::register' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HomepageController::menu' => ['privates', '.service_locator.QMnY7LW', 'get_ServiceLocator_QMnY7LWService', true],
            'App\\Controller\\MenuController::showAll' => ['privates', '.service_locator.QMnY7LW', 'get_ServiceLocator_QMnY7LWService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.B3Rkt.q', 'get_ServiceLocator_B3Rkt_QService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::userhomepage' => ['privates', '.service_locator.y09GgST', 'get_ServiceLocator_Y09GgSTService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AjoutDishController:onAddintionDishSuccess' => ['privates', '.service_locator.sk74CaS', 'get_ServiceLocator_Sk74CaSService', true],
            'App\\Controller\\AjoutDishController:register' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HomepageController:menu' => ['privates', '.service_locator.QMnY7LW', 'get_ServiceLocator_QMnY7LWService', true],
            'App\\Controller\\MenuController:showAll' => ['privates', '.service_locator.QMnY7LW', 'get_ServiceLocator_QMnY7LWService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.B3Rkt.q', 'get_ServiceLocator_B3Rkt_QService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:userhomepage' => ['privates', '.service_locator.y09GgST', 'get_ServiceLocator_Y09GgSTService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AjoutDishController::onAddintionDishSuccess' => '?',
            'App\\Controller\\AjoutDishController::register' => '?',
            'App\\Controller\\HomepageController::menu' => '?',
            'App\\Controller\\MenuController::showAll' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::userhomepage' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AjoutDishController:onAddintionDishSuccess' => '?',
            'App\\Controller\\AjoutDishController:register' => '?',
            'App\\Controller\\HomepageController:menu' => '?',
            'App\\Controller\\MenuController:showAll' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:userhomepage' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
