<?php

namespace ContainerZp4iImM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_BI7QKKdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.bI7QKKd' shared service.
     *
     * @return \App\Controller\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::userhomepage()": the $user argument is type-hinted with the non-existent class or interface: "App\\Controller\\User". Did you forget to add a use statement?');
    }
}
