<?php

namespace ContainerZp4iImM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sk74CaSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sk74CaS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sk74CaS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'token' => ['privates', '.errored..service_locator.sk74CaS.Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface', NULL, 'Cannot autowire service ".service_locator.sk74CaS": it references interface "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'token' => 'Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface',
        ]);
    }
}
