<?php

namespace ContainerZp4iImM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y09GgSTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y09GgST' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y09GgST'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored.bI7QKKd', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::userhomepage()": the $user argument is type-hinted with the non-existent class or interface: "App\\Controller\\User". Did you forget to add a use statement?'],
        ], [
            'user' => '?',
        ]);
    }
}
