<?php

namespace ContainerZp4iImM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTokenInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sk74CaS.Symfony\Component\Security\Core\Authentication\Token\TokenInterface' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authentication\Token\TokenInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sk74CaS": it references interface "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
