<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFUDPkfE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFUDPkfE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFUDPkfE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFUDPkfE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFUDPkfE\App_KernelDevDebugContainer([
    'container.build_hash' => 'FUDPkfE',
    'container.build_id' => '1e4fb60f',
    'container.build_time' => 1648731703,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFUDPkfE');
