<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQlY9oOm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQlY9oOm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQlY9oOm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQlY9oOm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQlY9oOm\App_KernelDevDebugContainer([
    'container.build_hash' => 'QlY9oOm',
    'container.build_id' => 'f6382813',
    'container.build_time' => 1649715626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQlY9oOm');
