<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFCqih0g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFCqih0g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFCqih0g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFCqih0g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFCqih0g\App_KernelDevDebugContainer([
    'container.build_hash' => 'FCqih0g',
    'container.build_id' => '071d81f0',
    'container.build_time' => 1648651704,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFCqih0g');
